#nama action
name: Kasmir Test

#trigger
on:
  push:
    branches:
      - main

#jobs
jobs:
  build:
    #where? runner
    runs-on: macos-latest
    #what? job
    steps:
      - name: Checkout repo dulu gan!
        uses: actions/checkout@v4

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage

      - name: build apk
        run: flutter build apk --release

      - name: upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: apk-v1.apk
          #path ke apk yang dihasilkan
          path: build/app/outputs/flutter-apk/app-release.apk
